#!/bin/bash

function c () {
	echo -e "\n*** path.log: BEGIN ***"
	/bin/cat -e "$HOME"/dotfiles/bash/log/path.log
	echo -e "\n*** path.log: END ***"
	echo -e "\nPATH:"
	echo "$PATH" | /usr/bin/sed -E -n 's/:/'$'\\\n''/g;p'
}

function sc() {
	. bash_profile
	c
}

function npc () {
	PATH=
	sc
}
